### ISSUE TITLE
Не подцепляет параметр для дефолтной папки

### ISSUE THREAD

**Issue by Flyer3d** [bem-tools/bem-tools-create#18]
Добрый день!

При таком файле конфига в дефолтной папке я ожидаю получить четыре файла на выходе ("bemtree.js", "styl", "js", "deps.js"), а создается только два ("styl", "js")

```
module.exports = {
    "root": true,
    "levels": {
        "common.blocks": {
        },
        "project.blocks": {
            "default": true
        }
    },
    "modules": {
        "bem-tools": {
            "plugins": {
                "create": {
                    "techs": [
                        "styl", "js"
                    ],
                    "templateFolder": "/Users/matveev/work/BEM/bem-tools-create/templates",
                    "levels": {
                        "project.blocks": {
                            "techs": ["bemtree.js", "styl", "js", "deps.js"],
                            "default": true
                        }
                    }
                }
            }
        }
    }
};
```

**Comment by xdevm** [comment]
Добрый вечер!

Проблема в том, что в файле `create.js` пути у `levelsMap` разворачиваются, а у `bemToolsConf` - нет

**Comment by xdevm** [comment]
Как вариант на время, пока не будет пофикшен баг, указать полный путь от корня у `common.blocks` и у `project.blocks`

**Comment by kompolom** [comment]
Тоже столкнулся с этой проблемой.
@tadatuta Если нет времени, но есть идея как пофиксить, напиши - пришлю PR

**Comment by tadatuta** [comment]
попробую вечером посмотреть

**Comment by tadatuta** [comment]
Выпустил bem-tools-create 2.0.0
