### ISSUE TITLE
Implement support for techs defined in config for levels

### ISSUE THREAD

**Issue by vithar** [bem-tools/bem-tools-create#4]
Techs specified in command-line must be merged
1. with techs specified for this level OR
2. with project techs OR
3. with global user techs

E.g.
`~/.bemconf.json`
```json
{
  "techs": [
      "js"
  ]
}
```

`~/project/bemconf.json`
```json
{
  "root": true,
  "techs": [
      "styl"
  ]
}
```

`~/project/level/bemconf.json`
```json
{
  "techs": [
      "css"
  ]
}
```
The command `bem create -t bemhtml b` creates block `b` with `bemhtml` and `css` techs.

@tadatuta, do I think in right direction?

**Comment by tadatuta** [comment]
yes, but we still need `forceTech` to create entities without regard of configs
